name: Deploy Backend to Cloud Run

on:
  push:
    branches: ['main']
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

env:
  SERVICE_NAME: realestate-backend
  REGION: ${{ secrets.GCP_REGION }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REPO: realestate-repo
  IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/realestate-repo/backend:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Print debug info
        run: |
          echo "GCP_REGION: ${{ secrets.GCP_REGION }}"
          echo "GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}"
          echo "IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/realestate-repo/backend:${{ github.sha }}"
          echo "Git SHA: ${{ github.sha }}"

      - name: Auth to Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet
          # 대안(문제시):
          # gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build & Push Backend Image
        working-directory: backend
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --platform managed \
            --region $REGION \
            --project $PROJECT_ID \
            --allow-unauthenticated \
            --port 8080 \
            --set-env-vars PORT=8080 \
            --set-env-vars DATABASE_URL='${{ secrets.DATABASE_URL }}' \
            --set-env-vars CORS_ORIGIN='${{ secrets.CORS_ORIGIN }}' \
            --set-env-vars AUTH_AUDIENCE='${{ secrets.AUTH_AUDIENCE }}' \
            --set-env-vars AUTH_ISSUER_BASE_URL='${{ secrets.AUTH_ISSUER_BASE_URL }}' \
            --set-env-vars AUTH_TOKEN_SIGNING_ALG='${{ secrets.AUTH_TOKEN_SIGNING_ALG }}'
