name: Diagnose GAR push

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  REGION: ${{ secrets.GCP_REGION }} # 예: us-west2
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # 예: realestate-app-475806
  REPO: realestate-repo
  IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/realestate-repo/diag:${{ github.sha }}

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show secrets used (masked)
        run: |
          echo "REGION=$REGION"
          echo "PROJECT_ID=$PROJECT_ID"
          echo "IMAGE=$IMAGE"

      - name: Install gcloud & activate SA
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Who am I?
        run: |
          gcloud --version
          gcloud config list
          gcloud auth list
          gcloud projects describe "$PROJECT_ID" --format="value(projectNumber)"

      - name: Configure docker to GAR (standard)
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Configure docker to GAR (access-token)
        run: |
          gcloud auth print-access-token | \
          docker login -u oauth2accesstoken --password-stdin https://$REGION-docker.pkg.dev

      - name: Build tiny image
        run: |
          cat <<'EOF' > Dockerfile
          FROM busybox
          CMD ["echo","hello"]
          EOF
          docker build -t "$IMAGE" .

      - name: Try pushing to GAR
        run: |
          docker push "$IMAGE"
